{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "4ea7eefd_c7260505",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 4146
      },
      "writtenOn": "2023-02-02T01:08:01Z",
      "side": 1,
      "message": "One concern related to my concern in the parent change and the other item is super minor. Again +2 and feel free to approve if we sure these concerns are not really a problem.",
      "revId": "9048706d93aa60ac414a7f5a1f94eda21a670cf9",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "9ce24345_36e98e0e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 27582
      },
      "writtenOn": "2023-02-03T09:27:04Z",
      "side": 1,
      "message": "recheck",
      "revId": "9048706d93aa60ac414a7f5a1f94eda21a670cf9",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "3a24f7d0_47addf65",
        "filename": "zuul/scheduler.py",
        "patchSetId": 5
      },
      "lineNbr": 1763,
      "author": {
        "id": 4146
      },
      "writtenOn": "2023-02-02T01:08:01Z",
      "side": 1,
      "message": "It seems most actions that could raise in _reconfigureDeletePipeline are wrapped in try blocks already and we log and ignore the errors there. Do we need to try and except here as well?",
      "revId": "9048706d93aa60ac414a7f5a1f94eda21a670cf9",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "b044efc1_4156bb3d",
        "filename": "zuul/scheduler.py",
        "patchSetId": 5
      },
      "lineNbr": 1763,
      "author": {
        "id": 27582
      },
      "writtenOn": "2023-02-02T06:32:27Z",
      "side": 1,
      "message": "You are right in that we already handle most of the exceptions in `_reconfigureDeletePipeline()`. The main idea there was to cleanup as much as possible without stopping on the first exception. But there are still things that could fail. I\u0027m mainly thinking about the `pipeline.state.refresh(ctx)` here.\n\nI think in general we shouldn\u0027t abort a tenant reconfiguration by letting an exception bubble up when a step is not required to complete the reconfig. So this is more of a better-safe-than-sorry exception handling here.",
      "parentUuid": "3a24f7d0_47addf65",
      "revId": "9048706d93aa60ac414a7f5a1f94eda21a670cf9",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "1d3619a0_629e577f",
        "filename": "zuul/scheduler.py",
        "patchSetId": 5
      },
      "lineNbr": 1913,
      "author": {
        "id": 4146
      },
      "writtenOn": "2023-02-02T01:08:01Z",
      "side": 1,
      "message": "Questions about safe tenant and pipeline names in the parent change would apply here as well.",
      "revId": "9048706d93aa60ac414a7f5a1f94eda21a670cf9",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "9368164d_5e5f090d",
        "filename": "zuul/scheduler.py",
        "patchSetId": 5
      },
      "lineNbr": 1913,
      "author": {
        "id": 1
      },
      "writtenOn": "2023-02-02T01:28:46Z",
      "side": 1,
      "message": "See parent change for more detail, but for the moment at least, this appears to be correct for event queues.",
      "parentUuid": "1d3619a0_629e577f",
      "revId": "9048706d93aa60ac414a7f5a1f94eda21a670cf9",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}