{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "887bd4b8_ecb7ac9d",
        "filename": "zuul/driver/sql/sqlconnection.py",
        "patchSetId": 1
      },
      "lineNbr": 266,
      "author": {
        "id": 1
      },
      "writtenOn": "2022-03-16T23:59:18Z",
      "side": 1,
      "message": "I\u0027m on the fence about this:\n\nWhile it\u0027s true that this can add some protection to using a broken connection, because we only keep idle connections for 1 second, it would only protect us in the situation where:\n\n* We sucessfully used a connection less than a second ago.\n* The connection has broken since then.\n* The connection will be automatically fixed within sqlalchemy\u0027s 3 retry attempts (I\u0027m not sure how long that is).\n\nThere isn\u0027t much overhead to this change, but there\u0027s some, and maybe it\u0027s not worth the vanishingly small chance that it actually helps?\n\nOn the other hand, maybe we can make the reporting handling more robust so that it doesn\u0027t have cascading failure effects.",
      "revId": "f58fd617cf6a5a8fe3408b794b13ec154e967d79",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}